### PR TITLE
Workaround incase error raised by --stop-min-lr during BART Training and also fixed Typo in preprocess-roberta-classifier.sh which stopped Domain 1 Validation Set from Being Read

### PR DESCRIPTION
**Pull request by aflah02**
I encountered this error and after some googling found a mailing group conversation which is a successful workaround - https://groups.google.com/g/fairseq-users/c/WAbE5wTLnjQ

### CODE REVIEW

**Comment by aflah02** [comment]
This now also fixes https://github.com/machelreid/lewis/issues/7

**Comment by aflah02** [comment]
Also fixed installation command now and wrong arg names in one of the commands

**Comment by aflah02** [comment]
@machelreid I've fixed almost everything which was causing an Issue, the last command is also wrong however fixing that is a bit more complex essentially the paths asked for and the paths the code uses are different

**Comment by aflah02** [comment]
@machelreid Just noticed that this PR is still open, are there any mistakes?

**Comment by machelreid** [comment]
LGTM! Sorry for the really delayed response, I completely missed this.

**Pull request merged**
